"""initial schema (24 entities + ops tables)

Revision ID: 42f9f7f51afa
Revises: 
Create Date: 2026-09-22 18:31:30.081791
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '42f9f7f51afa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=10), server_default=sa.text("'fr'"), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'Europe/Paris'"), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('coach','client')", name=op.f('ck_user_account_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('email', name=op.f('uq_user_account_email'))
    )
    op.create_index(op.f('ix_user_account_created_at'), 'user_account', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_account_role'), 'user_account', ['role'], unique=False)
    op.create_index(op.f('ix_user_account_updated_at'), 'user_account', ['updated_at'], unique=False)
    op.create_table('active_client_snapshot',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_account.id'], name=op.f('fk_active_client_snapshot_client_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['user_account.id'], name=op.f('fk_active_client_snapshot_coach_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_client_snapshot')),
    sa.UniqueConstraint('coach_id', 'client_id', 'period_month', name='uq_active_client_snapshot_period')
    )
    op.create_index(op.f('ix_active_client_snapshot_created_at'), 'active_client_snapshot', ['created_at'], unique=False)
    op.create_index(op.f('ix_active_client_snapshot_period_month'), 'active_client_snapshot', ['period_month'], unique=False)
    op.create_index(op.f('ix_active_client_snapshot_updated_at'), 'active_client_snapshot', ['updated_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user_account.id'], name=op.f('fk_audit_log_actor_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_subject_id'), 'audit_log', ['subject_id'], unique=False)
    op.create_index('ix_audit_log_subject_occurred', 'audit_log', ['subject_id', 'occurred_at'], unique=False)
    op.create_table('body_measurement',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg_enc', sa.LargeBinary(), nullable=True),
    sa.Column('body_fat_pct_enc', sa.LargeBinary(), nullable=True),
    sa.Column('waist_cm_enc', sa.LargeBinary(), nullable=True),
    sa.Column('hip_cm_enc', sa.LargeBinary(), nullable=True),
    sa.Column('chest_cm_enc', sa.LargeBinary(), nullable=True),
    sa.Column('arm_cm_enc', sa.LargeBinary(), nullable=True),
    sa.Column('thigh_cm_enc', sa.LargeBinary(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('client','coach')", name=op.f('ck_body_measurement_source_valid')),
    sa.ForeignKeyConstraint(['client_id'], ['user_account.id'], name=op.f('fk_body_measurement_client_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_measurement'))
    )
    op.create_index('ix_body_measurement_client_at', 'body_measurement', ['client_id', 'measured_at'], unique=False)
    op.create_index(op.f('ix_body_measurement_created_at'), 'body_measurement', ['created_at'], unique=False)
    op.create_index(op.f('ix_body_measurement_updated_at'), 'body_measurement', ['updated_at'], unique=False)
    op.create_table('client_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('birth_date_enc', sa.LargeBinary(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('height_cm_enc', sa.LargeBinary(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_client_profile_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_client_profile_user_id'))
    )
    op.create_index(op.f('ix_client_profile_created_at'), 'client_profile', ['created_at'], unique=False)
    op.create_index(op.f('ix_client_profile_trial_ends_at'), 'client_profile', ['trial_ends_at'], unique=False)
    op.create_index(op.f('ix_client_profile_updated_at'), 'client_profile', ['updated_at'], unique=False)
    op.create_table('coach_client_link',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('coaching_mode', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("coaching_mode IN ('presentiel','distance')", name=op.f('ck_coach_client_link_mode_valid')),
    sa.CheckConstraint("status IN ('pending','active','paused','revoked')", name=op.f('ck_coach_client_link_status_valid')),
    sa.CheckConstraint('coach_id <> client_id', name=op.f('ck_coach_client_link_no_self_link')),
    sa.ForeignKeyConstraint(['client_id'], ['user_account.id'], name=op.f('fk_coach_client_link_client_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['user_account.id'], name=op.f('fk_coach_client_link_coach_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_client_link'))
    )
    op.create_index(op.f('ix_coach_client_link_created_at'), 'coach_client_link', ['created_at'], unique=False)
    op.create_index(op.f('ix_coach_client_link_status'), 'coach_client_link', ['status'], unique=False)
    op.create_index(op.f('ix_coach_client_link_updated_at'), 'coach_client_link', ['updated_at'], unique=False)
    op.create_index('ix_link_coach_status', 'coach_client_link', ['coach_id', 'status'], unique=False)
    op.create_index('uq_link_one_active_per_client', 'coach_client_link', ['client_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('coach_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialties', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('offers_nutrition', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_coaching_mode', sa.String(length=16), server_default=sa.text("'distance'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_coach_profile_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_coach_profile_user_id'))
    )
    op.create_index(op.f('ix_coach_profile_created_at'), 'coach_profile', ['created_at'], unique=False)
    op.create_index(op.f('ix_coach_profile_updated_at'), 'coach_profile', ['updated_at'], unique=False)
    op.create_table('consent',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('tos','privacy','health_data','progress_photos','marketing')", name=op.f('ck_consent_purpose_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_consent_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent'))
    )
    op.create_index(op.f('ix_consent_created_at'), 'consent', ['created_at'], unique=False)
    op.create_index(op.f('ix_consent_updated_at'), 'consent', ['updated_at'], unique=False)
    op.create_index('ix_consent_user_purpose', 'consent', ['user_id', 'purpose', 'created_at'], unique=False)
    op.create_table('data_request',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('export_key', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execute_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('export','deletion')", name=op.f('ck_data_request_type_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_data_request_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_request'))
    )
    op.create_index(op.f('ix_data_request_created_at'), 'data_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_request_execute_after'), 'data_request', ['execute_after'], unique=False)
    op.create_index(op.f('ix_data_request_expires_at'), 'data_request', ['expires_at'], unique=False)
    op.create_index(op.f('ix_data_request_updated_at'), 'data_request', ['updated_at'], unique=False)
    op.create_index('ix_data_request_user_type', 'data_request', ['user_id', 'type', 'status'], unique=False)
    op.create_table('device_token',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('ios','android')", name=op.f('ck_device_token_platform_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_device_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_token')),
    sa.UniqueConstraint('token', name='uq_device_token_token')
    )
    op.create_index(op.f('ix_device_token_created_at'), 'device_token', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_token_updated_at'), 'device_token', ['updated_at'], unique=False)
    op.create_table('encryption_key',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('kek_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_encryption_key_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encryption_key')),
    sa.UniqueConstraint('user_id', name='uq_encryption_key_user_id'),
    sa.UniqueConstraint('user_id', name=op.f('uq_encryption_key_user_id'))
    )
    op.create_index(op.f('ix_encryption_key_created_at'), 'encryption_key', ['created_at'], unique=False)
    op.create_index(op.f('ix_encryption_key_updated_at'), 'encryption_key', ['updated_at'], unique=False)
    op.create_table('exercise',
    sa.Column('owner_coach_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_muscles', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('secondary_muscles', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('equipment', sa.String(length=64), nullable=True),
    sa.Column('mechanic', sa.String(length=32), nullable=True),
    sa.Column('force', sa.String(length=32), nullable=True),
    sa.Column('image_keys', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('video_key', sa.Text(), nullable=True),
    sa.Column('video_thumbnail_key', sa.Text(), nullable=True),
    sa.Column('media_license', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(source = 'seed' AND owner_coach_id IS NULL) OR (source = 'coach' AND owner_coach_id IS NOT NULL)", name=op.f('ck_exercise_source_matches_owner')),
    sa.CheckConstraint("media_license IN ('public_domain','coach_owned')", name=op.f('ck_exercise_media_license_valid')),
    sa.CheckConstraint("source IN ('seed','coach')", name=op.f('ck_exercise_source_valid')),
    sa.ForeignKeyConstraint(['owner_coach_id'], ['user_account.id'], name=op.f('fk_exercise_owner_coach_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise')),
    sa.UniqueConstraint('external_ref', name=op.f('uq_exercise_external_ref'))
    )
    op.create_index(op.f('ix_exercise_created_at'), 'exercise', ['created_at'], unique=False)
    op.create_index(op.f('ix_exercise_equipment'), 'exercise', ['equipment'], unique=False)
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=False)
    op.create_index(op.f('ix_exercise_owner_coach_id'), 'exercise', ['owner_coach_id'], unique=False)
    op.create_index('ix_exercise_primary_muscles', 'exercise', ['primary_muscles'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_exercise_updated_at'), 'exercise', ['updated_at'], unique=False)
    op.create_table('idempotency_record',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_idempotency_record_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_record')),
    sa.UniqueConstraint('user_id', 'endpoint', 'key', name='uq_idempotency_scope')
    )
    op.create_index(op.f('ix_idempotency_record_created_at'), 'idempotency_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_record_expires_at'), 'idempotency_record', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_record_updated_at'), 'idempotency_record', ['updated_at'], unique=False)
    op.create_table('invitation',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('email_hint', sa.Text(), nullable=True),
    sa.Column('coaching_mode', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("coaching_mode IN ('presentiel','distance')", name=op.f('ck_invitation_mode_valid')),
    sa.ForeignKeyConstraint(['coach_id'], ['user_account.id'], name=op.f('fk_invitation_coach_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consumed_by'], ['user_account.id'], name=op.f('fk_invitation_consumed_by_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation'))
    )
    op.create_index(op.f('ix_invitation_code'), 'invitation', ['code'], unique=True)
    op.create_index(op.f('ix_invitation_created_at'), 'invitation', ['created_at'], unique=False)
    op.create_index(op.f('ix_invitation_updated_at'), 'invitation', ['updated_at'], unique=False)
    op.create_table('notification',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_notification_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_scheduled_for'), 'notification', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notification_updated_at'), 'notification', ['updated_at'], unique=False)
    op.create_index('ix_notification_user_scheduled', 'notification', ['user_id', 'scheduled_for'], unique=False)
    op.create_table('nutrition_plan',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kcal_target_enc', sa.LargeBinary(), nullable=True),
    sa.Column('protein_g_enc', sa.LargeBinary(), nullable=True),
    sa.Column('carbs_g_enc', sa.LargeBinary(), nullable=True),
    sa.Column('fat_g_enc', sa.LargeBinary(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name=op.f('ck_nutrition_plan_status_valid')),
    sa.ForeignKeyConstraint(['client_id'], ['user_account.id'], name=op.f('fk_nutrition_plan_client_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['user_account.id'], name=op.f('fk_nutrition_plan_coach_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_plan'))
    )
    op.create_index('ix_nutrition_plan_client', 'nutrition_plan', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_nutrition_plan_created_at'), 'nutrition_plan', ['created_at'], unique=False)
    op.create_index(op.f('ix_nutrition_plan_updated_at'), 'nutrition_plan', ['updated_at'], unique=False)
    op.create_table('program',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("client_id IS NOT NULL OR status <> 'published'", name=op.f('ck_program_template_not_published')),
    sa.CheckConstraint("status IN ('draft','published','archived')", name=op.f('ck_program_status_valid')),
    sa.CheckConstraint('ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on', name=op.f('ck_program_dates_ordered')),
    sa.ForeignKeyConstraint(['client_id'], ['user_account.id'], name=op.f('fk_program_client_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['user_account.id'], name=op.f('fk_program_coach_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program'))
    )
    op.create_index(op.f('ix_program_client_id'), 'program', ['client_id'], unique=False)
    op.create_index('ix_program_coach_status', 'program', ['coach_id', 'status'], unique=False)
    op.create_index(op.f('ix_program_created_at'), 'program', ['created_at'], unique=False)
    op.create_index(op.f('ix_program_status'), 'program', ['status'], unique=False)
    op.create_index(op.f('ix_program_updated_at'), 'program', ['updated_at'], unique=False)
    op.create_table('refresh_token',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_token.id'], name=op.f('fk_refresh_token_replaced_by_refresh_token'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_refresh_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token'))
    )
    op.create_index(op.f('ix_refresh_token_created_at'), 'refresh_token', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_family_id'), 'refresh_token', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_token_updated_at'), 'refresh_token', ['updated_at'], unique=False)
    op.create_table('subscription',
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=16), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('manual','stripe')", name=op.f('ck_subscription_provider_valid')),
    sa.CheckConstraint("status IN ('trialing','active','past_due','canceled')", name=op.f('ck_subscription_status_valid')),
    sa.CheckConstraint("subject_type IN ('client','coach')", name=op.f('ck_subscription_subject_type_valid')),
    sa.ForeignKeyConstraint(['subject_id'], ['user_account.id'], name=op.f('fk_subscription_subject_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription'))
    )
    op.create_index(op.f('ix_subscription_created_at'), 'subscription', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_status'), 'subscription', ['status'], unique=False)
    op.create_index('ix_subscription_subject', 'subscription', ['subject_type', 'subject_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscription_trial_ends_at'), 'subscription', ['trial_ends_at'], unique=False)
    op.create_index(op.f('ix_subscription_updated_at'), 'subscription', ['updated_at'], unique=False)
    op.create_table('billing_event',
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'EUR'"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('provider_event_id', sa.Text(), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_billing_event_subscription_id_subscription'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_event')),
    sa.UniqueConstraint('provider_event_id', name=op.f('uq_billing_event_provider_event_id'))
    )
    op.create_index(op.f('ix_billing_event_created_at'), 'billing_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_event_subscription_id'), 'billing_event', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_event_updated_at'), 'billing_event', ['updated_at'], unique=False)
    op.create_table('conversation',
    sa.Column('coach_client_link_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_client_link_id'], ['coach_client_link.id'], name=op.f('fk_conversation_coach_client_link_id_coach_client_link'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation')),
    sa.UniqueConstraint('coach_client_link_id', name=op.f('uq_conversation_coach_client_link_id'))
    )
    op.create_index(op.f('ix_conversation_created_at'), 'conversation', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_last_message_at'), 'conversation', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversation_updated_at'), 'conversation', ['updated_at'], unique=False)
    op.create_table('meal',
    sa.Column('nutrition_plan_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kcal_enc', sa.LargeBinary(), nullable=True),
    sa.Column('macros_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slot IN ('breakfast','lunch','dinner','snack')", name=op.f('ck_meal_slot_valid')),
    sa.ForeignKeyConstraint(['nutrition_plan_id'], ['nutrition_plan.id'], name=op.f('fk_meal_nutrition_plan_id_nutrition_plan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal'))
    )
    op.create_index(op.f('ix_meal_created_at'), 'meal', ['created_at'], unique=False)
    op.create_index(op.f('ix_meal_updated_at'), 'meal', ['updated_at'], unique=False)
    op.create_table('program_session',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_index >= 0', name=op.f('ck_program_session_day_index_positive')),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_program_session_program_id_program'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_session'))
    )
    op.create_index(op.f('ix_program_session_created_at'), 'program_session', ['created_at'], unique=False)
    op.create_index('ix_program_session_program_day', 'program_session', ['program_id', 'day_index'], unique=False)
    op.create_index(op.f('ix_program_session_scheduled_date'), 'program_session', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_program_session_updated_at'), 'program_session', ['updated_at'], unique=False)
    op.create_table('progress_photo',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('angle', sa.String(length=16), nullable=False),
    sa.Column('shared_with_coach', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('consent_id', sa.UUID(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("angle IN ('front','side','back')", name=op.f('ck_progress_photo_angle_valid')),
    sa.ForeignKeyConstraint(['client_id'], ['user_account.id'], name=op.f('fk_progress_photo_client_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consent_id'], ['consent.id'], name=op.f('fk_progress_photo_consent_id_consent'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_photo'))
    )
    op.create_index('ix_progress_photo_client_at', 'progress_photo', ['client_id', 'taken_at'], unique=False)
    op.create_index(op.f('ix_progress_photo_created_at'), 'progress_photo', ['created_at'], unique=False)
    op.create_index(op.f('ix_progress_photo_updated_at'), 'progress_photo', ['updated_at'], unique=False)
    op.create_table('message',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body_enc', sa.LargeBinary(), nullable=False),
    sa.Column('attachment_key', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_message_conversation_id_conversation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user_account.id'], name=op.f('fk_message_sender_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_index('ix_message_conversation_sent', 'message', ['conversation_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_sent_at'), 'message', ['sent_at'], unique=False)
    op.create_index(op.f('ix_message_updated_at'), 'message', ['updated_at'], unique=False)
    op.create_table('nutrition_log',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('followed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('comment_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_account.id'], name=op.f('fk_nutrition_log_client_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], name=op.f('fk_nutrition_log_meal_id_meal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_log')),
    sa.UniqueConstraint('client_id', 'meal_id', 'date', name='uq_nutrition_log_day')
    )
    op.create_index('ix_nutrition_log_client_date', 'nutrition_log', ['client_id', 'date'], unique=False)
    op.create_index(op.f('ix_nutrition_log_created_at'), 'nutrition_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_nutrition_log_updated_at'), 'nutrition_log', ['updated_at'], unique=False)
    op.create_table('session_exercise',
    sa.Column('program_session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_load_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.String(length=16), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_load_kg IS NULL OR target_load_kg >= 0', name=op.f('ck_session_exercise_target_load_positive')),
    sa.CheckConstraint('target_reps IS NULL OR target_reps >= 0', name=op.f('ck_session_exercise_target_reps_positive')),
    sa.CheckConstraint('target_sets > 0', name=op.f('ck_session_exercise_target_sets_positive')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_session_exercise_exercise_id_exercise'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_session_id'], ['program_session.id'], name=op.f('fk_session_exercise_program_session_id_program_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_exercise'))
    )
    op.create_index(op.f('ix_session_exercise_created_at'), 'session_exercise', ['created_at'], unique=False)
    op.create_index('ix_session_exercise_session', 'session_exercise', ['program_session_id', 'position'], unique=False)
    op.create_index(op.f('ix_session_exercise_updated_at'), 'session_exercise', ['updated_at'], unique=False)
    op.create_table('workout_log',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('program_session_id', sa.UUID(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('total_volume_kg', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned','in_progress','completed','skipped')", name=op.f('ck_workout_log_status_valid')),
    sa.CheckConstraint('rpe IS NULL OR (rpe BETWEEN 1 AND 10)', name=op.f('ck_workout_log_rpe_range')),
    sa.CheckConstraint('total_volume_kg >= 0', name=op.f('ck_workout_log_volume_positive')),
    sa.ForeignKeyConstraint(['client_id'], ['user_account.id'], name=op.f('fk_workout_log_client_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_session_id'], ['program_session.id'], name=op.f('fk_workout_log_program_session_id_program_session'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_log')),
    sa.UniqueConstraint('client_id', 'idempotency_key', name='uq_workout_log_idempotency')
    )
    op.create_index('ix_workout_log_client_performed', 'workout_log', ['client_id', 'performed_at'], unique=False)
    op.create_index(op.f('ix_workout_log_created_at'), 'workout_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_workout_log_updated_at'), 'workout_log', ['updated_at'], unique=False)
    op.create_table('set_log',
    sa.Column('workout_log_id', sa.UUID(), nullable=False),
    sa.Column('session_exercise_id', sa.UUID(), nullable=True),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('reps_done', sa.Integer(), nullable=True),
    sa.Column('load_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rest_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('load_kg IS NULL OR load_kg >= 0', name=op.f('ck_set_log_load_positive')),
    sa.CheckConstraint('reps_done IS NULL OR reps_done >= 0', name=op.f('ck_set_log_reps_positive')),
    sa.CheckConstraint('set_index >= 0', name=op.f('ck_set_log_set_index_positive')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_set_log_exercise_id_exercise'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercise.id'], name=op.f('fk_set_log_session_exercise_id_session_exercise'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_log.id'], name=op.f('fk_set_log_workout_log_id_workout_log'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_log')),
    sa.UniqueConstraint('workout_log_id', 'session_exercise_id', 'set_index', name='uq_set_log_position')
    )
    op.create_index(op.f('ix_set_log_created_at'), 'set_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_set_log_updated_at'), 'set_log', ['updated_at'], unique=False)
    op.create_table('personal_record',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('load_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('estimated_1rm', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('set_log_id', sa.UUID(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user_account.id'], name=op.f('fk_personal_record_client_id_user_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_personal_record_exercise_id_exercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_log_id'], ['set_log.id'], name=op.f('fk_personal_record_set_log_id_set_log'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_record'))
    )
    op.create_index('ix_personal_record_client_exercise', 'personal_record', ['client_id', 'exercise_id', 'achieved_at'], unique=False)
    op.create_index(op.f('ix_personal_record_created_at'), 'personal_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_personal_record_updated_at'), 'personal_record', ['updated_at'], unique=False)
    # ### end Alembic commands ###

    _post_schema_upgrade()


def _post_schema_upgrade() -> None:
    """Hand-written additions that autogenerate cannot express."""

    # --- 1. Case-insensitive e-mail --------------------------------------
    # ARCHITECTURE.md §4 specifies citext. Without it "Bob@x.fr" and "bob@x.fr"
    # would be two accounts, and account recovery would be ambiguous.
    op.execute("ALTER TABLE user_account ALTER COLUMN email TYPE citext")

    # --- 2. updated_at maintained by the database ------------------------
    # SQLAlchemy's onupdate only fires for ORM-issued UPDATEs. `GET /sync?since=`
    # relies on updated_at, so a row modified by raw SQL, a migration or a Celery
    # bulk update must still become visible to the mobile app's delta sync —
    # otherwise a client silently never receives that change.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in _TIMESTAMPED_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
            """
        )


#: Every table carrying TimestampMixin (i.e. all but the append-only audit_log).
_TIMESTAMPED_TABLES = (
    "user_account",
    "coach_profile",
    "client_profile",
    "coach_client_link",
    "invitation",
    "refresh_token",
    "encryption_key",
    "exercise",
    "program",
    "program_session",
    "session_exercise",
    "workout_log",
    "set_log",
    "personal_record",
    "body_measurement",
    "progress_photo",
    "nutrition_plan",
    "meal",
    "nutrition_log",
    "conversation",
    "message",
    "notification",
    "device_token",
    "consent",
    "data_request",
    "subscription",
    "billing_event",
    "active_client_snapshot",
    "idempotency_record",
)


def downgrade() -> None:
    for table in _TIMESTAMPED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    _downgrade_schema()


def _downgrade_schema() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_record_updated_at'), table_name='personal_record')
    op.drop_index(op.f('ix_personal_record_created_at'), table_name='personal_record')
    op.drop_index('ix_personal_record_client_exercise', table_name='personal_record')
    op.drop_table('personal_record')
    op.drop_index(op.f('ix_set_log_updated_at'), table_name='set_log')
    op.drop_index(op.f('ix_set_log_created_at'), table_name='set_log')
    op.drop_table('set_log')
    op.drop_index(op.f('ix_workout_log_updated_at'), table_name='workout_log')
    op.drop_index(op.f('ix_workout_log_created_at'), table_name='workout_log')
    op.drop_index('ix_workout_log_client_performed', table_name='workout_log')
    op.drop_table('workout_log')
    op.drop_index(op.f('ix_session_exercise_updated_at'), table_name='session_exercise')
    op.drop_index('ix_session_exercise_session', table_name='session_exercise')
    op.drop_index(op.f('ix_session_exercise_created_at'), table_name='session_exercise')
    op.drop_table('session_exercise')
    op.drop_index(op.f('ix_nutrition_log_updated_at'), table_name='nutrition_log')
    op.drop_index(op.f('ix_nutrition_log_created_at'), table_name='nutrition_log')
    op.drop_index('ix_nutrition_log_client_date', table_name='nutrition_log')
    op.drop_table('nutrition_log')
    op.drop_index(op.f('ix_message_updated_at'), table_name='message')
    op.drop_index(op.f('ix_message_sent_at'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_index('ix_message_conversation_sent', table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_progress_photo_updated_at'), table_name='progress_photo')
    op.drop_index(op.f('ix_progress_photo_created_at'), table_name='progress_photo')
    op.drop_index('ix_progress_photo_client_at', table_name='progress_photo')
    op.drop_table('progress_photo')
    op.drop_index(op.f('ix_program_session_updated_at'), table_name='program_session')
    op.drop_index(op.f('ix_program_session_scheduled_date'), table_name='program_session')
    op.drop_index('ix_program_session_program_day', table_name='program_session')
    op.drop_index(op.f('ix_program_session_created_at'), table_name='program_session')
    op.drop_table('program_session')
    op.drop_index(op.f('ix_meal_updated_at'), table_name='meal')
    op.drop_index(op.f('ix_meal_created_at'), table_name='meal')
    op.drop_table('meal')
    op.drop_index(op.f('ix_conversation_updated_at'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_last_message_at'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_created_at'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_billing_event_updated_at'), table_name='billing_event')
    op.drop_index(op.f('ix_billing_event_subscription_id'), table_name='billing_event')
    op.drop_index(op.f('ix_billing_event_created_at'), table_name='billing_event')
    op.drop_table('billing_event')
    op.drop_index(op.f('ix_subscription_updated_at'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_trial_ends_at'), table_name='subscription')
    op.drop_index('ix_subscription_subject', table_name='subscription')
    op.drop_index(op.f('ix_subscription_status'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_created_at'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_refresh_token_updated_at'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_family_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_created_at'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_program_updated_at'), table_name='program')
    op.drop_index(op.f('ix_program_status'), table_name='program')
    op.drop_index(op.f('ix_program_created_at'), table_name='program')
    op.drop_index('ix_program_coach_status', table_name='program')
    op.drop_index(op.f('ix_program_client_id'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_nutrition_plan_updated_at'), table_name='nutrition_plan')
    op.drop_index(op.f('ix_nutrition_plan_created_at'), table_name='nutrition_plan')
    op.drop_index('ix_nutrition_plan_client', table_name='nutrition_plan')
    op.drop_table('nutrition_plan')
    op.drop_index('ix_notification_user_scheduled', table_name='notification')
    op.drop_index(op.f('ix_notification_updated_at'), table_name='notification')
    op.drop_index(op.f('ix_notification_scheduled_for'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_invitation_updated_at'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_created_at'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_code'), table_name='invitation')
    op.drop_table('invitation')
    op.drop_index(op.f('ix_idempotency_record_updated_at'), table_name='idempotency_record')
    op.drop_index(op.f('ix_idempotency_record_expires_at'), table_name='idempotency_record')
    op.drop_index(op.f('ix_idempotency_record_created_at'), table_name='idempotency_record')
    op.drop_table('idempotency_record')
    op.drop_index(op.f('ix_exercise_updated_at'), table_name='exercise')
    op.drop_index('ix_exercise_primary_muscles', table_name='exercise', postgresql_using='gin')
    op.drop_index(op.f('ix_exercise_owner_coach_id'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_equipment'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_created_at'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_encryption_key_updated_at'), table_name='encryption_key')
    op.drop_index(op.f('ix_encryption_key_created_at'), table_name='encryption_key')
    op.drop_table('encryption_key')
    op.drop_index(op.f('ix_device_token_updated_at'), table_name='device_token')
    op.drop_index(op.f('ix_device_token_created_at'), table_name='device_token')
    op.drop_table('device_token')
    op.drop_index('ix_data_request_user_type', table_name='data_request')
    op.drop_index(op.f('ix_data_request_updated_at'), table_name='data_request')
    op.drop_index(op.f('ix_data_request_expires_at'), table_name='data_request')
    op.drop_index(op.f('ix_data_request_execute_after'), table_name='data_request')
    op.drop_index(op.f('ix_data_request_created_at'), table_name='data_request')
    op.drop_table('data_request')
    op.drop_index('ix_consent_user_purpose', table_name='consent')
    op.drop_index(op.f('ix_consent_updated_at'), table_name='consent')
    op.drop_index(op.f('ix_consent_created_at'), table_name='consent')
    op.drop_table('consent')
    op.drop_index(op.f('ix_coach_profile_updated_at'), table_name='coach_profile')
    op.drop_index(op.f('ix_coach_profile_created_at'), table_name='coach_profile')
    op.drop_table('coach_profile')
    op.drop_index('uq_link_one_active_per_client', table_name='coach_client_link', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_link_coach_status', table_name='coach_client_link')
    op.drop_index(op.f('ix_coach_client_link_updated_at'), table_name='coach_client_link')
    op.drop_index(op.f('ix_coach_client_link_status'), table_name='coach_client_link')
    op.drop_index(op.f('ix_coach_client_link_created_at'), table_name='coach_client_link')
    op.drop_table('coach_client_link')
    op.drop_index(op.f('ix_client_profile_updated_at'), table_name='client_profile')
    op.drop_index(op.f('ix_client_profile_trial_ends_at'), table_name='client_profile')
    op.drop_index(op.f('ix_client_profile_created_at'), table_name='client_profile')
    op.drop_table('client_profile')
    op.drop_index(op.f('ix_body_measurement_updated_at'), table_name='body_measurement')
    op.drop_index(op.f('ix_body_measurement_created_at'), table_name='body_measurement')
    op.drop_index('ix_body_measurement_client_at', table_name='body_measurement')
    op.drop_table('body_measurement')
    op.drop_index('ix_audit_log_subject_occurred', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_subject_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_active_client_snapshot_updated_at'), table_name='active_client_snapshot')
    op.drop_index(op.f('ix_active_client_snapshot_period_month'), table_name='active_client_snapshot')
    op.drop_index(op.f('ix_active_client_snapshot_created_at'), table_name='active_client_snapshot')
    op.drop_table('active_client_snapshot')
    op.drop_index(op.f('ix_user_account_updated_at'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_role'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_created_at'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
